### ISSUE TITLE
Sidecar that backs up WordPress

### ISSUE THREAD

**Issue by oliverdain** [MVPStudio/standard-wordpress#2]
This would be a small, simple container that runs in the same pod as the Wordpress image. It would share the main Wordpress volume mount but _also_ mount a different directory that is not accessible to the main Wordpress container. It would then backup the Wordpress volume and database regularly. Something roughly like:

```
while true
do
   # Sleep for a day
   sleep 86400
   mysqldump ... > /backup/backup-$(date).sql
   tar zcvf /back/backup-$(date).tar.gz /var/html
done
```

It should also clean up old files so we don't end up with too many backups. Maybe we have 1 week worth of backups and then one backup that's 1 month old and everything else get's deleted or something? It doesn't need to be bash - Python or whatever would work as well.

**Comment by colindavey** [comment]
Would it make sense for this to be kubernetes CronJob?

**Comment by colindavey** [comment]
I'll take a crack at it.

**Comment by colindavey** [comment]
This doesn't care which of the two setups from this issue are involved, right? https://github.com/MVPStudio/standard-wordpress/issues/1

**Comment by oliverdain** [comment]
A cronjob does make sense but I _think_ (not sure - double check me) that a cron job can't be a side-car. That is, I don't think you can have a cron job that would run in the same pod as WordPress which would make it difficult to access the volume. We could mount the volume into the cron job as well I suppose.

We might instead want to use something like wp-backup plugin: https://wordpress.org/plugins/backupwordpress/

I think the key criteria are:

1. Backups are automatic
2. Backups are stored to a volume that the main Wordpress container can't access. That way if the WordPess container gets compromised the attacker can't delete the backups
3. We save several backups including at least one that's several weeks old in case a site breaks or is compromised and nobody notices for a while.
4. We don't store more than `n` old backups so we don't just use more and more disk space.

**Comment by colindavey** [comment]
Do we know exactly which files need to be backed up, eg everything in a specific directory?

**Comment by colindavey** [comment]
You are correct, as usual, about there being issues about pod and volume with cron job. 

I have a running start here. https://github.com/MVPStudio/standard-wordpress/tree/feature/wp_bak

I'm just doing sleep() in python while loop.

**Comment by oliverdain** [comment]
I'm gong to take a crack at getting this working as a side car.
